# Build stage
FROM node:22-alpine

WORKDIR /app

# Create apps/web directory and copy its package.json
COPY package.json .

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# # Build application
# RUN npm run build

CMD [ "npm", "run", "build" ]